version: "3"
services:

  selenium-hub:
    image: selenium/hub:4.0.0-alpha-6-20200730
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.0.0-alpha-6-20200730
    volumes:
      - /dev/shm:/dev/shm
      - ./src/test/resources:/ui-test-automation-tdd/src/test/resources
    ports:
      - "5900:5900"
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - SCREEN_WIDTH=1280
